### ISSUE TITLE
Support capital letters

### ISSUE THREAD

**Issue by GSI** [udleinati/redirect.center#43]
Some URLs are case sensitive. For example MailChimp's shortened URL http://eepurl.com/F0obar differs from http://eepurl.com/f0obar.

So, eepurl.com.opts-slash.F0obar.redirect.center would lead to the wrong destination since DNS is case-insensitive.

**Comment by Virsacer** [comment]
Having the same problem...

Cant use .opts-query, because the "?" is inserted...
A copy of that function whithout the questionmark could be used for casesensitive data?

**Comment by jonasbru** [comment]
Hello, having the same problem with Trello ! Too bad as it was really hyped to have found an easy solution for custom domains :(

**Comment by Virsacer** [comment]
For `https://127.0.0.1/AaBbCc` the converter still suggests `127.0.0.1.opts-slash.AaBbCc.opts-https.redirect.center.` which does not work because of case(in)sensitivity.

When adding a ? like `https://127.0.0.1/?AaBbCc` it suggests `127.0.0.1.opts-slash.opts-query.ifqueysdmm.opts-https.redirect.center.`, but that redirects to `https://127.0.0.1.ifqueysdmm/opts-query`

**Comment by Virsacer** [comment]
Yes, this is working now, thank you
